import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"grid min-h-svh grid-rows-[auto_1fr_auto]"}>
        <header>My header</header>
        <main>{children}</main>
        <footer>My footer</footer>
      </body>
    </html>
  );
}
