import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/services/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import SessionProvider from "@/services/providers/session-provider";
import Header from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"grid min-h-svh grid-rows-[auto_1fr_auto]"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <Header />
            <main className="container mx-auto px-4">{children}</main>
            <Toaster />
            <footer>My footer</footer>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
