import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/services/providers/theme-provider";
import { ModeToggleButton } from "@/features/theme/components/mode-toggle-button";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"grid min-h-svh grid-rows-[auto_1fr_auto]"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header>
            <h1>CritiQ</h1>
            <ModeToggleButton />
          </header>
          <main>{children}</main>
          <Toaster />
          <footer>My footer</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
